version: "3.3"

services:
  app:
    image: node:current-alpine
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=qwerty
      - MYSQL_DBNAME=stock
      - BACKEND_PORT=4000
      - ROOT_FOLDER=ed4bf8f5-8b4e-435b-83cc-27feada6136a
    ports:
      - 4000:4000
    command: ["node", "/app/src/index.js"]

  mysql:
    image: mysql:5.7.19
    environment:
      - MYSQL_ROOT_PASSWORD=qwerty
    volumes:
      - ./test/mysql/dump:/docker-entrypoint-initdb.d
